# -*- coding: utf-8 -*-
"""Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18BmFR1StGQCK4w-Pnx7vYp0lb-Q6J9yK

First Example of List
"""

list1=[34,98,"sahithi","honey",34,"sam"]
print(list1)

len(list1)

list1.append("Ramu")
print(list1)

list1.insert(2,12)

print(list1)

list1[5]

list1[-3]

list1[::-1]

list1.extend(["pathi",76,"Raghav"])

print(list1)

list1.remove(34)

print(list1)

list1.pop()

"""2nd Example of list"""

n=int(input("Enter the number values"))
list2=[]
 
   
for i in range(n):
  x=[int(input("Enter the value ")),input("Enter the string values ")]
  list2.append(x)
print(list2)

import numpy
a=numpy.array(list2)
print(a.shape)

# For list of integers
lst1 = []

# For list of strings/chars
lst2 = []

lst1 = [int(item) for item in input("Enter the list items : ").split()]

lst2 = [item for item in input("Enter the list items : ").split()]

print(lst1)
print(lst2)

print("Before  using the pop function in list",list2)
def fun(n):
  list2.pop()
 
n=int(input("Enter the number of values removed "))
fun(n)
print("After  using the pop function in list", list2)

# maximum Number in list
max(list2)

#minimum number in list2
min(list2)

#sort the list2
list2.sort()
print(list2)

#Reverse the list2
list2.sort(reverse=True)
print(list2)

#update the value
list2[1][0]="23"
print(list2)

"""Tuple Examples
Example :1

"""

tup=(223,54,"jashu",98,"sahithi",76,88,"lakshmi")
print(tup)

#accesing the elemnents
tup[5]

#Represent a single element in a tuple 
tup1=(34,)
print(tup1)

#slicingthe elments
tup[2:5]

tup[::-1]

#updating elements
tup2=tup+tup1
print(tup2)

print("Before using the delete operation",tup)
del tup
print("After using the delete operation",tup)

len(tup2)

a=("Hi",)*4
print(a)

"""Example 2"""

tup3=(45,76,88,82,67,56)
for i in range(len(tup3)):
  print(tup3[i])

tup3[2:5]

print("Even numbers")
for  num in tup3:
   if num%2==0:
     print(num)

max(tup3)

min(tup3)

sum(tup3)

print(88 in tup3)

tup4=(45,"sah","dad","pathi")
print(tup4)

tup5=(tup3,tup4)
print(tup5)

"""Dictionary"""

#create a empty dictionary
dic1={}
print(dict)

Dict=dict({1:"sam",2:"kishore",3:"hani"})
print(Dict)

#create a nested dictionary
dict1={1:"orange",2:"apple",3:"minus",4:{'A':'welcome','B':'to','c':'world'}}
print(dict1)

print(Dict[3])

Dict.get(3)

#accessing the nested dictionary
print(dict1[2][4])

dict1.popitem()

print(dict1)

print(dict1.keys())

print(dict1.items())

dict1.update({2:"honey"})

print(dict1)

"""Set Examples"""

set1=set()
print(set1)

data=set(['kavya','karthika','vennela','teacher'])
print(data)

#adding an one element
data.add('nani')

print(data)

#remove an element from a dictionary
data.remove('karthika')
print(data)

#use the discard method to remove a value from a set.
data.discard('nani')

print(data)

data1=(6,7,8,9,10)
data.update(data1)
print(data)

for item in data:
  print(item)

#sorted array
sorted(data1,reverse=True)

dataScientist = set(['Python', 'R', 'SQL', 'Git', 'Tableau', 'SAS'])
dataEngineer = set(['Python', 'Java', 'Scala', 'Git', 'SQL', 'Hadoop'])

dataScientist.union(dataEngineer)

#intersection operation
dataScientist & dataEngineer

dataScientist - dataEngineer

dataScientist ^ dataEngineer

'R' in dataScientist

possibleSkills = {'Python', 'R', 'SQL', 'Git', 'Tableau', 'SAS'}
mySkills = {'Python', 'R'}

print(possibleSkills)

print(mySkills)

#Subset 
mySkills.issubset(possibleSkills)

"""Assignment-2

Read operation
"""

file = open("/content/sahithi.txt")

print(file.read())

"""Append"""

file1=open("/content/sahithi.txt","a")

file1.write("This is my file ")

with open("sahithi.txt") as file: 
   data = file.read()

with open("sahithi.txt", "r") as file:
    data = file.readlines()
    for line in data:
        word = line.split()
        print (word)

